### ISSUE TITLE
issue -  cannot import name 'Action' from 'composio' 

### ISSUE THREAD

**Issue by Madhuvod** [ComposioHQ/composio#1115]
I constantly get this error: I want to use the google docs tool or notion tool where my phidata agent writes its response by creating a new doc and writing in it. but I have been constantly facing this error. my python version is 3.12.7, any solutions pls? also the composio docs to use notion tool is very confusing, any simple workflow examples can help. thanks. the error:

```
(base) madhushantan@Madhus-MacBook-Air ai_personal_learning_agent % composio add googledocs
Traceback (most recent call last):
  File "/Users/madhushantan/.pyenv/versions/3.12.7/bin/composio", line 5, in <module>
    from composio.cli import cli
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/__init__.py", line 10, in
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/__init__.py", line 10, in <module>
    from composio.cli.actions import _actions
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/actions.py", line 13, in 
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/actions.py", line 13, in <module>
    from composio.cli.context import Context, pass_context
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/context.py", line 23, in 
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/context.py", line 23, in <module>
    from composio.tools.env.factory import WorkspaceType
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/tools/__init__.py", line 1, i
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/tools/__init__.py", line 1, in <module>
    from .toolset import ComposioToolSet
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/tools/toolset.py", line 23, i
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/tools/toolset.py", line 23, in <module>
    from composio import Action, ActionType, App, AppType, TagType
ImportError: cannot import name 'Action' from 'composio' (/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/si
ImportError: cannot import name 'Action' from 'composio' (/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/__init__.py)
```

**Comment by plxity** [comment]
@Madhuvod Thanks for reporting this, I'll check and update you.

**Comment by Madhuvod** [comment]
yes, thanks! pls lmk as soon as possible - working on a project and wanting to use Composio tools for it

**Comment by tushar-composio** [comment]
Hey, can you run the following commands and send us their output?
```
which composio
which pip
pip show composio
composio --version
```

**Comment by Madhuvod** [comment]
(base) madhushantan@Madhus-MacBook-Air ai_agent_tutorials % which composio
/Users/madhushantan/.pyenv/versions/3.12.7/bin/composio
(base) madhushantan@Madhus-MacBook-Air ai_agent_tutorials % which pip
/Users/madhushantan/.pyenv/versions/3.12.7/bin/pip
(base) madhushantan@Madhus-MacBook-Air ai_agent_tutorials % pip show composio
Name: composio
Version: 0.1.0
Summary: Composio Python SDK.
Home-page: https://github.com/tushar-composio/composio
Author: Tushar Sadhwani
Author-email: tushar@composio.dev
License: MIT
Location: /Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages
Requires: 
Required-by: 
(base) madhushantan@Madhus-MacBook-Air ai_agent_tutorials % composio --version
Traceback (most recent call last):
  File "/Users/madhushantan/.pyenv/versions/3.12.7/bin/composio", line 5, in <module>
    from composio.cli import cli
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/__init__.py", line 10, in <module>
    from composio.cli.actions import _actions
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/actions.py", line 13, in <module>
    from composio.cli.context import Context, pass_context
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/cli/context.py", line 23, in <module>
    from composio.tools.env.factory import WorkspaceType
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/tools/__init__.py", line 1, in <module>
    from .toolset import ComposioToolSet
  File "/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/tools/toolset.py", line 23, in <module>
    from composio import Action, ActionType, App, AppType, TagType
ImportError: cannot import name 'Action' from 'composio' (/Users/madhushantan/.pyenv/versions/3.12.7/lib/python3.12/site-packages/composio/__init__.py)

**Comment by Madhuvod** [comment]
@tushar-composio  can you solve this please

**Comment by tusharsadhwani** [comment]
Please do the following:

```
pip uninstall composio -y
pip install composio-core
```

**Comment by plxity** [comment]
@Madhuvod I'm Just following up. Did it work after running the above commands?

**Comment by tusharsadhwani** [comment]
@SakshiiKorat can you paste the output of the following commands?

```
which composio
which pip
pip show composio
pip show composio-core
composio --version
```

**Comment by SakshiiKorat** [comment]
(venv) PS D:\task\composio> where python
(venv) PS D:\task\composio> 

(venv) PS D:\task\composio> pip show composio
Name: composio
Version: 0.1.1
Summary: Shim for composio-core.
Home-page: https://github.com/tushar-composio/composio
Author: Tushar Sadhwani
Author-email: tushar@composio.dev
License: MIT
Location: D:\task\composio\venv\Lib\site-packages
Requires: composio-core
Required-by:

(venv) PS D:\task\composio> pip show composio-core
Name: composio_core
Version: 0.6.11.post1
Summary: Core package to act as a bridge between composio platform and other services.
Home-page: https://github.com/composiohq/composio
Author: Utkarsh
Author-email: utkarsh@composio.dev
License:
Location: D:\task\composio\venv\Lib\site-packages
Requires: aiohttp, click, fastapi, importlib-metadata, inflection, jsonref, jsonschema, paramiko, pydantic, pyperclip, pysher, requests, rich, semver, sentry-sdk, uvicorn
Required-by: composio, composio_langchain

(venv) PS D:\task\composio> composio --version
composio : The term 'composio' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ composio --version
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (composio:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by SakshiiKorat** [comment]
(venv) PS D:\task\composio> Get-Command pip

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pip.exe                                            0.0.0.0    D:\task\composio\venv\scripts\pip.exe

**Comment by SakshiiKorat** [comment]
*No composio Command-Line Interface (CLI):*

   - You attempted to run commands like composio --version, but no such
   executable exists because the installed packages (composio_core and
   composio_langchain) are Python libraries, not standalone CLI tools.
   -  Unsupported which Command in Windows PowerShell:
   -   When running your script (ragtool.py), errors occurred because
   composio_langchain tried to import symbols (Action, App) from a module
   named composio, which either doesn’t exist or has been
   refactored/removed.
   -   The issues likely stem from changes in the library’s API or a
   mismatch between library versions (composio_core and composio_langchain)
   where expected components (like Action or App) are no longer provided as
   before.

**Comment by Madhuvod** [comment]
@plxity @tusharsadhwani it is indeed working for me. but I have a doubt tho. for me to use a particular composio tool - lets say google docs's - Create new document action, do I need to do anything else apart from these two step:

```
composio add googledocs

select OAUTH2 → SELECT GOOGLE ACCOUNT
```
and I get final output as:

>  ⚠ Waiting for googledocs authentication...
> ✔ googledocs added successfully with ID: 227fdfe1-2fe9-4f42-a6d3-2f3777374b89

for the 2nd step:

> TO https://app.composio.dev/app/googledocs AND click create integration and click Try connecting default’s googldocs button and done.

Apart from this and using the composio api key in our code, anything else needs to be done?

**Comment by SakshiiKorat** [comment]
composio add googledocs
when i am running this command it is showing that
"the term 'composio' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was"

We have already installed composio version and also there is composio_core
version and composio_langchain is there then why it is showing the error
that composio is not there?
.

**Comment by plxity** [comment]
@SakshiiKorat @Madhuvod This issue should be fixed. Can you try again and let me know if you have any issues?

**Comment by plxity** [comment]
Closing this issue, feel free to open it if you face any issues.
